neo4j_api:
  image: chvb/docker-apache-php
  container_name: neo4j_front
  restart: always
  volumes:
    - ./mock/:/var/www:rw
  ports:
    - "52000:80"

neo4j_front:
  build: ./html
  container_name: neo4j_front
  restart: always
  volumes:
    - ./html:/usr/src/node:rw
  ports:
    - "52001:80"